{% set name = "shapash" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shapash-{{ version }}.tar.gz
  sha256: 8a76a11e30f7739eb27fe366f4ef76587cc7b9ae24422706a9e392e44186059b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pytest-runner
    - pip
    - nodejs
    - tk  # legacy?
    - xorg-libx11   # legacy?
  run:
    - python >=3.7,<3.11
    - plotly >=5.0.0
    - matplotlib-base >=3.2.0
    - numpy >1.18.0
    - pandas >1.0.2
    - shap >=0.38.1
    - flask <2.3.0
    - dash >=2.3.1
    - dash-bootstrap-components >=1.1.0
    - dash-core-components >=2.0.0
    - dash-daq >=0.5.0
    - dash-html-components >=2.0.0
    - dash-renderer ==1.8.3
    - dash-table >=5.0.0
    - nbformat >4.2.0
    - numba >=0.53.1
    - scikit-learn >=1.0.1
    - category_encoders >=2.6.0
    - scipy >=0.19.1
    - xorg-libx11  # legacy?
# This list should be identical to the list in shapash/report/__init__.py
    - ipython
    - nbconvert >=6.0.7
    - papermill >=2.0.0
    - jupyter_client <8.0.0
    - seaborn >=0.12.2
    - notebook
    - jinja2 >=2.11.0
    - phik
# extras_require=extras,
    - xgboost >=1.0.0
    - lightgbm >=2.3.0
    - catboost >=1.0.1
    - acv-exp >=1.2.0
    - lime >=0.2.0.0
# pip check failure- dash 2.11.1 has requirement Werkzeug<2.3.0, but you have werkzeug 2.3.6.
    - Werkzeug <2.3.0

test:
  imports:
    - shapash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MAIF/shapash
  summary: Shapash is a Python library which aims to make machine learning interpretable and understandable by everyone.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
