{% set name = "shapash" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shapash-{{ version }}.tar.gz
  sha256: 6d862eb896313e34694826450ef9a546360727ae16227d6d3260cc8fa0372b77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pytest-runner
    - pip
    - nodejs
    - tk
    - xorg-libx11
  run:
    - python >=3.7,<3.11
    - plotly >=5.0.0
    - matplotlib-base >=3.2.0
    - numpy >1.18.0
    - pandas >1.0.2
    - shap >=0.38.1
    - dash >=2.3.1
    - dash-bootstrap-components >=1.1.0
    - dash-core-components >=2.0.0
    - dash-daq >=0.5.0
    - dash-html-components >=2.0.0
    - dash-renderer ==1.8.3
    - dash-table >=5.0.0
    - nbformat >4.2.0
    - numba >=0.53.1
    - scikit-learn >=0.24.0
    - category_encoders >=2.2.2
    - scipy >=0.19.1
    - xorg-libx11

    - ipython
    - nbconvert >=6.0.7
    - papermill >=2.0.0
    - seaborn >=0.11.0
    - notebook
    - jinja2 >=2.11.0
    - phik

test:
  imports:
    - shapash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MAIF/shapash
  summary: Shapash is a Python library which aims to make machine learning interpretable and understandable by everyone.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
